-- ============================================================================
-- Migration: Public profiles (2026-06)
-- ----------------------------------------------------------------------------
-- Adds OPTIONAL columns to the existing `leaderboard` table so that clickable
-- public profiles (reached via #/u/<userId>) can show a LinkedIn link, a
-- per-room solved breakdown, and the user's current employment (company + role)
-- which doubles as the referral payload + the monthly "is this still current?"
-- reminder.
--
-- The application is written to DEGRADE GRACEFULLY before this runs:
--   * fetchPublicProfile() selects the rich columns first (incl. current_company,
--     current_role, company_updated_at) and retries with the base columns if any
--     are absent.
--   * updateMyLinkedin() / updateMyEmployment() / confirmMyEmployment() return
--     { ok:false, reason:'migration-pending' } (and the UI falls back to
--     localStorage) if their columns are missing.
--   * upsertLeaderboardRow() retries without room_breakdown / linkedin_url if
--     those columns do not exist.
-- Running this migration simply lets those values persist server-side.
--
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent).
-- ============================================================================

-- 1. New columns ------------------------------------------------------------
-- linkedin_url:       the user's LinkedIn profile URL (nullable, optional).
-- room_breakdown:     a small JSON map of { roomId: solvedCount }, e.g.
--                     { "stats": 8, "sql-lab": 23, "rca": 4 }.
-- current_company:    the user's current employer, a canonical value from
--                     src/data/companyList.js COMPANIES (nullable, optional).
-- current_role:       the user's current role, from PROFILE_ROLES (nullable).
-- company_updated_at: when the employment was last set/confirmed. The monthly
--                     in-app reminder shows when this is null or older than 30
--                     days; the "Still accurate" button bumps it to now().
-- email_reminded_at:  when the monthly EMAIL reminder edge function last emailed
--                     this user (throttle so it never double-sends in a cycle).
--                     Used only by supabase/functions/employment-reminder.
-- resume_url:         public (or signed) URL of the user's uploaded résumé PDF,
--                     stored in the 'resumes' Storage bucket at `${uid}/resume.pdf`.
--                     Shown as a "View résumé" link on the public profile (opt-in
--                     by virtue of the user uploading it). Nullable.
-- resume_updated_at:  when the résumé was last uploaded/replaced. Nullable.
alter table leaderboard
  add column if not exists linkedin_url       text,
  add column if not exists room_breakdown     jsonb,
  add column if not exists current_company    text,
  add column if not exists current_role       text,
  add column if not exists company_updated_at timestamptz,
  add column if not exists email_reminded_at  timestamptz,
  add column if not exists resume_url         text,
  add column if not exists resume_updated_at  timestamptz;

-- 2. Row Level Security -----------------------------------------------------
-- The leaderboard is ALREADY publicly readable. The original schema created:
--   create policy "Public read leaderboard" on leaderboard for select using (true);
--   create policy "Users upsert own row" on leaderboard
--     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
--
-- Those policies operate at the ROW level and automatically cover any new
-- columns (Postgres RLS is not column-scoped here). The public profile page
-- reads the same rows the leaderboard already exposes, and each user still
-- only writes their own row — including the new linkedin_url / room_breakdown.
--
-- => NO NEW RLS POLICY IS REQUIRED for public profile reads or for users
--    updating their own LinkedIn / breakdown. The existing policies suffice.
--
-- The block below is a DEFENSIVE no-op that (re)asserts those two policies in
-- case this is run against an environment where they were never created.
-- It is safe to leave commented out if your policies already exist.

-- alter table leaderboard enable row level security;
--
-- do $$
-- begin
--   if not exists (
--     select 1 from pg_policies
--     where schemaname = 'public' and tablename = 'leaderboard'
--       and policyname = 'Public read leaderboard'
--   ) then
--     create policy "Public read leaderboard" on leaderboard
--       for select using (true);
--   end if;
--
--   if not exists (
--     select 1 from pg_policies
--     where schemaname = 'public' and tablename = 'leaderboard'
--       and policyname = 'Users upsert own row'
--   ) then
--     create policy "Users upsert own row" on leaderboard
--       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
--   end if;
-- end $$;

-- ============================================================================
-- 3. Storage bucket for résumé uploads  (REQUIRED for the résumé feature)
-- ----------------------------------------------------------------------------
-- The résumé feature uploads a PDF to a Storage bucket named 'resumes' at the
-- path `${auth.uid()}/resume.pdf` and writes the resulting URL to
-- leaderboard.resume_url (added above).
--
-- Buckets CANNOT be created from this SQL editor migration the same way a table
-- is — create the bucket in the Supabase Dashboard (Storage -> New bucket), then
-- run the policy SQL below. The app DEGRADES GRACEFULLY until this exists:
-- uploadResume() returns { ok:false, reason:'storage-pending' } (bucket missing)
-- or 'migration-pending' (resume_url column missing) instead of throwing, and the
-- UI shows "Saved locally — syncing soon". See docs/RESUME-UPLOAD-SETUP.md.
--
-- STEPS:
--   1. Dashboard -> Storage -> New bucket
--        Name:   resumes
--        Public: ON   (simplest — résumés are reachable via a public URL on the
--                      public profile. If you prefer private, leave Public OFF;
--                      uploadResume() falls back to a 1-year signed URL.)
--   2. Run the RLS policies below in the SQL editor (operate on storage.objects).
--
-- Each user may upload/update/delete ONLY objects under their own `${uid}/...`
-- prefix; résumés are readable for the public profile.
--
-- -- (a) Anyone can read objects in the 'resumes' bucket (public profile link).
-- --     Skip this if the bucket is Public ON (already world-readable) AND you
-- --     use public URLs; keep it if you want explicit control.
-- create policy "Public read resumes"
--   on storage.objects for select
--   using ( bucket_id = 'resumes' );
--
-- -- (b) A user can upload only into their own folder: resumes/<their-uid>/...
-- create policy "Users upload own resume"
--   on storage.objects for insert
--   with check (
--     bucket_id = 'resumes'
--     and (storage.foldername(name))[1] = auth.uid()::text
--   );
--
-- -- (c) A user can overwrite (upsert) only their own résumé.
-- create policy "Users update own resume"
--   on storage.objects for update
--   using (
--     bucket_id = 'resumes'
--     and (storage.foldername(name))[1] = auth.uid()::text
--   );
--
-- -- (d) A user can delete only their own résumé.
-- create policy "Users delete own resume"
--   on storage.objects for delete
--   using (
--     bucket_id = 'resumes'
--     and (storage.foldername(name))[1] = auth.uid()::text
--   );

-- ============================================================================
-- End migration.
-- ============================================================================
